export const POOLS_LIST_TOP_TAB = 'DODO_WIDGET_POOL_LIST_TOP_TAB';
export const POOLS_LIST_TAB = 'DODO_WIDGET_POOL_LIST_TAB';
export const POOLS_LIST_FILTER_CHAIN = 'DODO_WIDGET_POOLS_LIST_FILTER_CHAIN';
